apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: seguridad-pipeline-
spec:
  entrypoint: seguridad-ci
  templates:
    - name: seguridad-ci
      steps:
        - - name: semgrep-scan
            template: semgrep
        - - name: trivy-scan
            template: trivy

    - name: semgrep
      container:
        image: returntocorp/semgrep
        command: [sh, -c]
        args: ["semgrep --config=auto /mnt/code"]
        volumeMounts:
          - name: code-volume
            mountPath: /mnt/code

    - name: trivy
      container:
        image: aquasec/trivy
        command: [sh, -c]
        args: ["trivy fs /mnt/code"]
        volumeMounts:
          - name: code-volume
            mountPath: /mnt/code

  volumes:
    - name: code-volume
      emptyDir: {}
